import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/navbar";

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["600"], // Add this line (or any weights you want)
  variable: "--font-spectral",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spectral.variable}>
      <body style={{ fontFamily: "var(--font-spectral), serif" }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
